import { 
  AppCredentials, 
  AuditRecord, 
  BankAccount,
  BankDepositRecord,
  BroadcastNotification, 
  CreditClientLoan,
  FuelRates, 
  Partner, 
  PartnerWithdrawal, 
  StationBalance, 
  StationEntry 
} from './types';

export const INITIAL_CREDENTIALS: AppCredentials = {
  partnerPin: '1234',
  managerPin: '5678',
  adminPin: '1122', // CEO/Admin Jalees default PIN
};

export const INITIAL_PARTNERS: Partner[] = [
  {
    id: 'part-1',
    name: 'Shafiq',
    role: 'Lead Partner',
    investment: 2000000,
    phone: '+92 300 5551234',
    notes: 'Lead investor & operations executive',
    joinedDate: '2026-01-01',
  },
  {
    id: 'part-2',
    name: 'Habib',
    role: 'Silent Investor',
    investment: 1706500,
    phone: '+92 301 5555678',
    notes: 'Strategic capital partner',
    joinedDate: '2026-01-15',
  },
  {
    id: 'part-3',
    name: 'Nasir',
    role: 'Investment Partner',
    investment: 1950000,
    phone: '+92 302 5559012',
    notes: 'Capital & commercial oversight',
    joinedDate: '2026-02-01',
  },
  {
    id: 'part-4',
    name: 'Jalees',
    role: 'CEO & Managing Partner',
    investment: 2040850,
    phone: '+92 300 7771122',
    notes: 'Executive Authority & Administrator',
    joinedDate: '2026-01-01',
  },
];

export const INITIAL_WITHDRAWALS: PartnerWithdrawal[] = [
  {
    id: 'w-1',
    partnerId: 'part-1',
    partnerName: 'Shafiq',
    date: '2026-08-30',
    amount: 150000,
    paymentMode: 'Bank Transfer',
    reference: 'HBL-99238',
    notes: 'August interim profit withdrawal',
    recordedBy: 'Admin Jalees',
    createdAt: '2026-08-30T10:30:00Z',
  },
  {
    id: 'w-2',
    partnerId: 'part-4',
    partnerName: 'Jalees',
    date: '2026-09-01',
    amount: 180000,
    paymentMode: 'Bank Transfer',
    reference: 'MCB-44120',
    notes: 'Executive draw - Q3 dividend advance',
    recordedBy: 'Admin Jalees',
    createdAt: '2026-09-01T14:15:00Z',
  },
];

export const INITIAL_RATES: FuelRates = {
  psr: 375.0, // Petrol Sale Rate
  ppr: 355.0, // Petrol Purchase Rate
  dsr: 374.0, // Diesel Sale Rate
  dpr: 353.5, // Diesel Purchase Rate
  hosr: 420.0, // Hi-Octane 97 Sale Rate
  hopr: 395.0, // Hi-Octane 97 Purchase Rate
  lsr: 1250.0, // Lubes Sale Rate
  lpr: 1100.0, // Lubes Purchase Rate
  lastUpdated: '2026-09-10T08:00:00Z',
  updatedBy: 'CEO Jalees',
};

export const INITIAL_STATION_BALANCES: StationBalance[] = [
  {
    id: 'stn-swat-1',
    station: 'SWAT 1',
    status: 'Active',
    allocatedInvestment: 0, // Reset as requested
    cashOnHand: 0,          // Reset as requested
    petrolCapacity: 10000,
    dieselCapacity: 10000,
    lubesCapacity: 2000,
    hiOctaneCapacity: 5000,
    petrolStock: 5200,
    dieselStock: 4800,
    lubesStock: 450,
    hiOctaneStock: 2100,
    supportsPetrol: true,
    supportsDiesel: true,
    supportsHiOctane: true,
    typeOfTanks: 'Underground Double-Walled Steel',
    tanksCount: 3,
    dispensersCount: 4,
    nozzlesCount: 8,
    managerInCharge: 'Tariq Khan',
    location: 'Main Mingora Bypass, Swat',
    phone: '+92 345 9112233',
  },
  {
    id: 'stn-swat-2',
    station: 'SWAT 2',
    status: 'Active',
    allocatedInvestment: 0, // Reset as requested
    cashOnHand: 0,          // Reset as requested
    petrolCapacity: 8000,
    dieselCapacity: 8000,
    lubesCapacity: 1500,
    hiOctaneCapacity: 4000,
    petrolStock: 4100,
    dieselStock: 3950,
    lubesStock: 380,
    hiOctaneStock: 1600,
    supportsPetrol: true,
    supportsDiesel: true,
    supportsHiOctane: true,
    typeOfTanks: 'Underground Cylindrical Fiberglass',
    tanksCount: 3,
    dispensersCount: 3,
    nozzlesCount: 6,
    managerInCharge: 'Ihsan Ullah',
    location: 'Kabal Road, Swat',
    phone: '+92 333 9887711',
  },
  {
    id: 'stn-swat-3',
    station: 'SWAT 3',
    status: 'Active',
    allocatedInvestment: 2800000,
    cashOnHand: 840000,
    petrolCapacity: 10000,
    dieselCapacity: 10000,
    lubesCapacity: 2000,
    hiOctaneCapacity: 5000,
    petrolStock: 6100,
    dieselStock: 5800,
    lubesStock: 520,
    hiOctaneStock: 3100,
    supportsPetrol: true,
    supportsDiesel: true,
    supportsHiOctane: true,
    typeOfTanks: 'Underground Double-Walled Steel',
    tanksCount: 3,
    dispensersCount: 4,
    nozzlesCount: 8,
    managerInCharge: 'Zubair Shah',
    location: 'Saidu Sharif Express, Swat',
    phone: '+92 312 8844332',
  },
  {
    id: 'stn-pcr-1',
    station: 'PCR 1',
    status: 'Active',
    allocatedInvestment: 1800000,
    cashOnHand: 430000,
    petrolCapacity: 6000,
    dieselCapacity: 6000,
    lubesCapacity: 1000,
    hiOctaneCapacity: 0,
    petrolStock: 3400,
    dieselStock: 3100,
    lubesStock: 310,
    hiOctaneStock: 0,
    supportsPetrol: true,
    supportsDiesel: true,
    supportsHiOctane: false,
    typeOfTanks: 'Underground Composite Horizontal',
    tanksCount: 2,
    dispensersCount: 2,
    nozzlesCount: 4,
    managerInCharge: 'Kamran Ali',
    location: 'Peshawar Cantt Sector A',
    phone: '+92 300 5511224',
  },
  {
    id: 'stn-pcr-2',
    station: 'PCR 2',
    status: 'Active',
    allocatedInvestment: 1600000,
    cashOnHand: 375000,
    petrolCapacity: 6000,
    dieselCapacity: 6000,
    lubesCapacity: 1000,
    hiOctaneCapacity: 0,
    petrolStock: 2950,
    dieselStock: 2750,
    lubesStock: 280,
    hiOctaneStock: 0,
    supportsPetrol: true,
    supportsDiesel: true,
    supportsHiOctane: false,
    typeOfTanks: 'Underground Composite Horizontal',
    tanksCount: 2,
    dispensersCount: 2,
    nozzlesCount: 4,
    managerInCharge: 'Waseem Akram',
    location: 'Ring Road Interchange, Peshawar',
    phone: '+92 346 7722119',
  },
];

// Note: All entries before today (2026-09-15) are purged as requested.
// Only today's active verified operations remain.
export const INITIAL_ENTRIES: StationEntry[] = [
  {
    id: 'ent-today-swat3',
    station: 'SWAT 3',
    date: '2026-09-15',
    petrolSales: 450.0,
    petrolPurchase: 500.0,
    petrolSaleRate: 375.0,
    petrolPurchaseRate: 355.0,
    petrolOldPurchaseRate: 353.0,
    petrolMarginMode: 'average_stock',
    petrolNozzleSaleReading: 450.0,
    petrolNozzlePurchaseReading: 500.0,
    dieselSales: 380.0,
    dieselPurchase: 400.0,
    dieselSaleRate: 374.0,
    dieselPurchaseRate: 353.5,
    dieselOldPurchaseRate: 352.0,
    dieselMarginMode: 'average_stock',
    dieselNozzleSaleReading: 380.0,
    dieselNozzlePurchaseReading: 400.0,
    hiOctaneSales: 120.0,
    hiOctanePurchase: 150.0,
    hiOctaneSaleRate: 420.0,
    hiOctanePurchaseRate: 395.0,
    hiOctaneOldPurchaseRate: 390.0,
    hiOctaneMarginMode: 'average_stock',
    hiOctaneNozzleSaleReading: 120.0,
    hiOctaneNozzlePurchaseReading: 150.0,
    lubesSales: 12.0,
    lubesPurchase: 15.0,
    lubesSaleRate: 1250.0,
    lubesPurchaseRate: 1100.0,
    salaries: 3000,
    wages: 1500,
    food: 800,
    travel: 400,
    maintenance: 500,
    otherExpenses: 200,
    grossProfit: 450 * (375 - 354) + 380 * (374 - 352.75) + 120 * (420 - 392.5) + 12 * 150,
    totalExpenses: 6400,
    netProfit: (450 * 21 + 380 * 21.25 + 120 * 27.5 + 12 * 150) - 6400,
    revenue: 450 * 375 + 380 * 374 + 120 * 420 + 12 * 1250,
    nozzleVariance: 0.0,
    purchaseNozzleVariance: 0.0,
    auditFlag: false,
    notes: "Today's opening verified closing shift",
    createdBy: 'CEO Jalees',
    createdAt: '2026-09-15T08:00:00Z',
  },
];

export const INITIAL_AUDITS: AuditRecord[] = [
  {
    id: 'aud-today-01',
    station: 'SWAT 1',
    date: '2026-09-15',
    type: 'missing_closing',
    title: 'SWAT 1 & SWAT 2 Investment & Entry Reset Confirmation',
    description: 'Executive command executed: Sales, purchases, and allocated investments for SWAT 1 & SWAT 2 reset to 0.',
    severity: 'low',
    status: 'Completed',
    actionTakenBy: 'CEO Jalees',
    actionTakenAt: '2026-09-15T07:30:00Z',
    actionNotes: 'Verified at baseline. Stations ready for fresh calibration and capital infusion.',
  },
  {
    id: 'aud-today-02',
    station: 'PCR 2',
    date: '2026-09-15',
    type: 'tank_warning',
    title: 'Diesel Underground Tank Alert < 35%',
    description: 'Underground diesel reserve dip measurement shows 2,750 L remaining.',
    severity: 'medium',
    status: 'Pending',
  },
];

export const INITIAL_NOTIFICATIONS: BroadcastNotification[] = [
  {
    id: 'notif-today-1',
    timestamp: '2026-09-15T08:15:00Z',
    title: 'SWAT 1 & SWAT 2 Investments & Entries Cleared',
    message: 'All previous sales, purchases, and capital allocations for SWAT 1 & 2 have been cleared to zero baseline.',
    type: 'entry_reset',
    actor: 'CEO Jalees',
    station: 'SWAT 1',
    read: false,
  },
  {
    id: 'notif-today-2',
    timestamp: '2026-09-15T08:00:00Z',
    title: 'System Purge: Historical Pre-Today Data Pruned',
    message: 'In accordance with executive directives, all entries and logs preceding today (2026-09-15) were wiped.',
    type: 'system',
    actor: 'CEO Jalees',
    read: false,
  },
];

export const INITIAL_BANK_ACCOUNTS: BankAccount[] = [
  {
    id: 'bank-1',
    bankName: 'Meezan Bank Limited',
    accountTitle: 'Kashfi Bro Holdings (Pvt) Ltd',
    accountNumber: '0102-0103482910',
    iban: 'PK64MEZN0001020103482910',
    branch: 'Mingora Main Branch, Swat',
    currentBalance: 4850000,
    isPrimary: true,
  },
  {
    id: 'bank-2',
    bankName: 'Habib Bank Limited (HBL)',
    accountTitle: 'Kashfi Bro Holdings - Operations',
    accountNumber: '2281-7901234503',
    iban: 'PK36HABB0022817901234503',
    branch: 'Saidu Sharif Branch, Swat',
    currentBalance: 2680000,
    isPrimary: false,
  },
  {
    id: 'bank-3',
    bankName: 'MCB Bank Limited',
    accountTitle: 'KBH Fuel Revenue Collection',
    accountNumber: '0891-1122334455',
    iban: 'PK12MUCB0891112233445501',
    branch: 'G.T. Road Branch, Peshawar',
    currentBalance: 1940000,
    isPrimary: false,
  },
];

export const INITIAL_BANK_DEPOSITS: BankDepositRecord[] = [
  {
    id: 'dep-1',
    date: '2026-09-15',
    station: 'SWAT 3',
    bankAccountId: 'bank-1',
    bankName: 'Meezan Bank Limited',
    accountNumber: '0102-0103482910',
    amount: 500000,
    depositType: 'Daily Cash',
    slipNumber: 'DEP-88410',
    depositedBy: 'Zubair Shah',
    notes: 'Shift morning cash collection deposit to primary account',
    createdAt: '2026-09-15T11:30:00Z',
  },
  {
    id: 'dep-2',
    date: '2026-09-15',
    station: 'PCR 1',
    bankAccountId: 'bank-2',
    bankName: 'Habib Bank Limited (HBL)',
    accountNumber: '2281-7901234503',
    amount: 350000,
    depositType: 'Net Profit',
    slipNumber: 'DEP-77312',
    depositedBy: 'Amjad Ali',
    notes: 'Operating profit credit from yesterday closing',
    createdAt: '2026-09-15T10:00:00Z',
  },
];

export const INITIAL_CREDIT_LOANS: CreditClientLoan[] = [
  {
    id: 'loan-1',
    clientName: 'NLC Goods Logistics Fleet',
    vehicleNo: 'TL-4920',
    fuelType: 'Diesel',
    liters: 300,
    rate: 374,
    amount: 112200,
    slipNumber: 'SLIP-9041',
    dueDate: '2026-09-25',
    status: 'Pending',
    notes: 'Approved 15-day fleet credit fuel voucher',
  },
  {
    id: 'loan-2',
    clientName: 'Swat Emergency Services',
    vehicleNo: 'GOV-118',
    fuelType: 'Petrol',
    liters: 150,
    rate: 375,
    amount: 56250,
    slipNumber: 'SLIP-9042',
    dueDate: '2026-09-30',
    status: 'Pending',
    notes: 'Govt emergency response ambulance monthly credit voucher',
  },
  {
    id: 'loan-3',
    clientName: 'Malik Brothers Dumper Fleet',
    vehicleNo: 'PK-993',
    fuelType: 'Diesel',
    liters: 450,
    rate: 374,
    amount: 168300,
    slipNumber: 'SLIP-9043',
    dueDate: '2026-09-20',
    status: 'Pending',
    notes: 'Highway construction gravel transport dumper',
  },
];

export const INITIAL_DIP_TESTS: DipTestRecord[] = [
  {
    id: 'dip-1',
    station: 'SWAT 3',
    date: '2026-09-15',
    shift: 'Morning (06:00)',
    fuelType: 'Petrol',
    tankNumber: 1,
    dipReadingMm: 1420,
    calculatedLiters: 14250,
    ledgerLiters: 14300,
    varianceLiters: -50,
    variancePercent: -0.35,
    waterDipMm: 0,
    conductedBy: 'Irfan Ullah',
    personResponsible: 'Saeed Khan',
    status: 'normal',
    notes: 'Morning shift opening dip. Clear paste, no water trace.',
    createdAt: '2026-09-15T06:15:00Z',
  },
  {
    id: 'dip-2',
    station: 'SWAT 3',
    date: '2026-09-15',
    shift: 'Morning (06:00)',
    fuelType: 'Diesel',
    tankNumber: 2,
    dipReadingMm: 1180,
    calculatedLiters: 11900,
    ledgerLiters: 11920,
    varianceLiters: -20,
    variancePercent: -0.17,
    waterDipMm: 0,
    conductedBy: 'Irfan Ullah',
    personResponsible: 'Saeed Khan',
    status: 'normal',
    notes: 'Underground diesel tank reading within acceptable tolerance.',
    createdAt: '2026-09-15T06:20:00Z',
  },
  {
    id: 'dip-3',
    station: 'PCR 1',
    date: '2026-09-15',
    shift: 'Morning (06:00)',
    fuelType: 'Diesel',
    tankNumber: 1,
    dipReadingMm: 980,
    calculatedLiters: 9850,
    ledgerLiters: 10080,
    varianceLiters: -230,
    variancePercent: -2.28,
    waterDipMm: 0,
    conductedBy: 'Shahid Mehmood',
    personResponsible: 'Kashif Mehmood',
    status: 'critical_variance',
    notes: 'Physical brass dip 230L below ATG ledger. Tank manifold inspection requested.',
    createdAt: '2026-09-15T06:30:00Z',
  },
];

export const INITIAL_DIP_SCHEDULES: DipTestScheduleItem[] = [
  {
    id: 'sched-swat1-m',
    station: 'SWAT 1',
    shift: 'Morning (06:00)',
    scheduledTime: '06:00 AM',
    managerInCharge: 'Tariq Khan',
    lastDipDate: '2026-09-14',
    lastDipShift: 'Evening (18:00)',
    lastDipVarianceLiters: -35,
    isOverdue: true,
    status: 'overdue',
  },
  {
    id: 'sched-swat2-m',
    station: 'SWAT 2',
    shift: 'Morning (06:00)',
    scheduledTime: '06:00 AM',
    managerInCharge: 'Arshad Ali',
    lastDipDate: '2026-09-14',
    lastDipShift: 'Evening (18:00)',
    lastDipVarianceLiters: -20,
    isOverdue: true,
    status: 'overdue',
  },
  {
    id: 'sched-swat3-m',
    station: 'SWAT 3',
    shift: 'Morning (06:00)',
    scheduledTime: '06:00 AM',
    managerInCharge: 'Saeed Khan',
    lastDipDate: '2026-09-15',
    lastDipShift: 'Morning (06:00)',
    lastDipVarianceLiters: -50,
    isOverdue: false,
    status: 'completed',
  },
  {
    id: 'sched-pcr1-m',
    station: 'PCR 1',
    shift: 'Morning (06:00)',
    scheduledTime: '06:00 AM',
    managerInCharge: 'Kashif Mehmood',
    lastDipDate: '2026-09-15',
    lastDipShift: 'Morning (06:00)',
    lastDipVarianceLiters: -230,
    isOverdue: false,
    status: 'completed',
  },
  {
    id: 'sched-pcr2-m',
    station: 'PCR 2',
    shift: 'Morning (06:00)',
    scheduledTime: '06:00 AM',
    managerInCharge: 'Waseem Akram',
    lastDipDate: '2026-09-14',
    lastDipShift: 'Evening (18:00)',
    lastDipVarianceLiters: -15,
    isOverdue: true,
    status: 'overdue',
  },
];

export const DEFAULT_DASHBOARD_LAYOUT: DashboardLayoutConfig = {
  sectionsOrder: [
    'kpi_banner',
    'stats_grid',
    'ai_alerts',
    'dip_test_widget',
    'market_pulse',
    'station_balances',
    'tank_stocks',
  ],
  hiddenSections: [],
  density: 'comfortable',
};

